version: "3.9"

services:
  tg_video_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_video_downloader
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /media/devmon/sda1-usb-Initio_INIC-3609/NAS/Video/Anime:/data/downloads
      - /media/devmon/sda1-usb-Initio_INIC-3609/NAS/Files/tg_video_downloader:/app
